### ISSUE TITLE
Aperture Alerting System

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#854]
## Description
* An Alertmanager compatible alerting system in Aperture
* This is an umbrella ticket

## Sub-tasks
- [x] https://github.com/fluxninja/aperture/issues/861
- [x] https://github.com/fluxninja/aperture/issues/608
- [x] https://github.com/fluxninja/aperture/issues/862
- [x] https://github.com/fluxninja/aperture/issues/863

**Comment by tanveergill** [comment]
@DariaKunoichi,
That should be all. Closing the ticket
