### ISSUE TITLE
Logic Combinators

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#868]
## Description
* Provide ability to do logical operations on boolean signals

## Sub-tasks
- [x] https://github.com/fluxninja/aperture/issues/865
- [x] https://github.com/fluxninja/aperture/issues/866
- [ ] https://github.com/fluxninja/aperture/issues/867
