### ISSUE TITLE
Remove JSON encoding/decoding from agent's datapath

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#880]
See the profile (json-related stuff highlighted in purple)

![image](https://user-images.githubusercontent.com/3074996/199506919-93562cf1-0316-4a4a-8830-bc01c59175c6.png)

JSON encoding/decoding takes about 40% of total agent runtime and occurs in the following places (left to right):
- [x] `key` in rollupprocessor – #1036 
- [x] `createExtAuthzResponse` in envoy authz Check (marshalling CheckResponse) – #881 
- [ ] `RequestToInput` in envoy authz Check
- [x] `GetStuct` used by metricsprocessor (unmarshalling CheckResponse) – #881 

All that JSON usage could be fairly simply avoided.

**Is your feature request related to a problem? Please describe.**
Agent's overhead is bigger than istio-proxy's overhead. We should aim for overhead lower than istio-proxy.

**Describe the solution you'd like**
JSON encoding should be avoided / replaced by other encoding

**Describe alternatives you've considered**
Some experiments by @kwapik with different json libraries didn't show too much improvement.

**Comment by kwapik** [comment]
For `key` we may consider https://github.com/mitchellh/hashstructure

**Comment by krdln** [comment]
Profiling agent:

1. ```
   kubectl port-forward aperture-agent-dkd9v 8333:8080 
   ```
2. ```
   go tool pprof 'http://localhost:8333/debug/pprof/profile?seconds=40
   ```
   this autosaves profile, you can also use commands to directly show profile, don't remember though. I think there are commands like `evince`, `png`?
3. to get flamegraph as in the screenshot (you don't have to do this though, I just like how flamegraphs look :))
    ```
    go tool pprof -raw -output=cpu-02-15.txt /home/michal/pprof/pprof.aperture-agent.samples.cpu.005.pb.gz
    ```
    (the gz filename is printed out by tool pprof previous command), and  for converting to flamegraph
    ```
    ~/bin/FlameGraph/stackcollapse-go.pl $x | ~/bin/FlameGraph/flamegraph.pl > $(basename --suffix .txt $x).svg  (this requires https://github.com/brendangregg/FlameGraph)
    ```
    then open in firefox/chrome and search for json (search box in embedded in svg in top-right)
